name: NPM Publish

on:
  push:
    tags:
      - '*'
      - '!*-beta*'
      - '!*-alpha*'
      - '!*-rc*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: npm run test:coverage

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: echo "//registry.npmjs.org/:_authToken=" > ~/.npmrc
      - run: npm publish --access public --provenance


  send-slack-message:
      needs: publish-npm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 22
        - run: bash ./scripts/release-notes.sh
          env:
            RELEASE_SLACK_WEBHOOK_URL: ${{secrets.RELEASE_SLACK_WEBHOOK_URL}}
